wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 64
Epoch:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704540198.441044
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.6
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
